[package]
name = "practicum"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
cuid = "1.2.0"
env_logger = "0.9.1"
log = "0.4.17"
tokio = { version = "1.21.1", features = ["full"] }
